spring:
  profiles: dev

server:
  port: 9090

---
spring:
    profiles: qa
    thymeleaf:
      check-template-location: false
      check-template: false
      prefix: classpath:/templates/
      suffix: .html
server:
    port: 7008